baseURL = "https://bsideszh.ch/"
languageCode = 'en-us'
title = 'BSides Zurich'
theme = 'ananke'
enableRobotsTXT = true

SectionPagesMenu = "main"

[params]
  text_color = "dark-gray"
  rel = "me noopener"
  site_logo = "images/bsides_logo_blue.jpg"
  favicon = "images/bszhicon.png"
  mainSections = ["updates"]
  custom_css = ["custom.css"]
  body_classes = "avenir bg-near-white"
  post_content_classes = "avenir"

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/BSidesZurich"

[[params.ananke_socials]]
  name = "mastodon"
  url = "https://infosec.exchange/@BSidesZurich"
