baseURL = "https://bsideszh.ch/"
languageCode = 'en-us'
title = 'BSides Zurich'
theme = 'ananke'

SectionPagesMenu = "main"

[params]
  text_color = "dark-gray"
  rel = "me noopener"
  site_logo = "images/bsides_logo_blue.jpg"

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/BSidesZurich"

[[params.ananke_socials]]
  name = "mastodon"
  url = "https://infosec.exchange/BSidesZurich"
